steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-west9-docker.pkg.dev/nestjs-microservices-506615/image-registry/auth-microservice',
        '-f',
        'Dockerfile',
        '--platform=linux/amd64',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-west9-docker.pkg.dev/nestjs-microservices-506615/image-registry/auth-microservice',
      ]
options:
  logging: CLOUD_LOGGING_ONLY
